version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
configuration:
- Debug
- Release
clone_folder: c:\dev\tlx
before_build:
- cmd: >-
    echo Running cmake...

    cd c:\dev\tlx

    md build

    cd build

    cmake -G "Visual Studio 14 Win64" -DTLX_BUILD_TESTS=ON -DTLX_TRY_COMPILE_HEADERS=ON -DTLX_MORE_TESTS=ON ..
build:
  project: c:\dev\tlx\build\tlx.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: ctest -V --build-config %CONFIGURATION%
